#ifndef LIB_H_ASLKDJFHASOIUEFHSOEIUFHASOIUDFGYHEROIGUHEROIGUH
#define LIB_H_ASLKDJFHASOIUEFHSOEIUFHASOIUDFGYHEROIGUHEROIGUH

#ifdef __cplusplus
extern "C"
#endif
void print_some();

#endif // #ifndef LIB_H_ASLKDJFHASOIUEFHSOEIUFHASOIUDFGYHEROIGUHEROIGUH
